TFile* file1 = new TFile("side0.root")
TFile* file2 = new TFile("side2.root")
TFile* file3 = new TFile("side4.root")
TH1D* hist1 = (TH1D*)file1->Get("scint_eioni")
TH1D* hist2 = (TH1D*)file2->Get("scint_eioni")
TH1D* hist3 = (TH1D*)file3->Get("scint_eioni")
TCanvas* c1 = new TCanvas("c1", "c1")
c1->Divide(2,2)
c1->cd(1)
hist1->Draw()
c1->cd(2)
hist2->Draw()
c1->cd(3)
hist3->Draw()

